// Generated by CoffeeScript 1.6.3
(function() {
  var a, b, c, isPalindrome, max, res, _i, _j;

  res = 0;

  isPalindrome = function(x) {
    var num;
    num = x;
    res = 0;
    while (num > 0) {
      res = res * 10 + num % 10;
      num = ~~(num / 10);
    }
    return (x - res) === 0;
  };

  max = 0;

  for (a = _i = 1; _i <= 999; a = ++_i) {
    for (b = _j = 1; _j <= 999; b = ++_j) {
      c = a * b;
      if (c > max && isPalindrome(c)) {
        max = c;
      }
    }
  }

  res = max;

  console.log(res);

}).call(this);
