// Generated by CoffeeScript 1.6.3
(function() {
  var N, i, j, n, res, sum, _i, _j, _ref;

  res = 0;

  N = 1001;

  n = 1;

  sum = 1;

  for (i = _i = 2, _ref = (N - 1) / 2 + 1; 2 <= _ref ? _i <= _ref : _i >= _ref; i = 2 <= _ref ? ++_i : --_i) {
    for (j = _j = 1; _j <= 4; j = ++_j) {
      n += 1 + 2 * (i - 2) + 1;
      console.log(i, n);
      sum += n;
    }
  }

  res = sum;

  console.log(res);

}).call(this);
