// Generated by CoffeeScript 1.6.3
(function() {
  var i, isPrime, j, res;

  res = 0;

  isPrime = function(n) {
    var i, _i, _ref;
    if (n === 2 || n === 3) {
      return true;
    }
    for (i = _i = 2, _ref = ~~Math.sqrt(n); 2 <= _ref ? _i <= _ref : _i >= _ref; i = 2 <= _ref ? ++_i : --_i) {
      if (n % i === 0) {
        return false;
      }
    }
    return true;
  };

  i = 1;

  j = 0;

  while (j !== 10001) {
    i++;
    if (isPrime(i)) {
      j++;
    }
  }

  res = i;

  console.log(res);

}).call(this);
