// Generated by CoffeeScript 1.6.3
(function() {
  var res, _i, _j, _results, _results1;

  res = 0;

  res = Math.pow((function() {
    _results = [];
    for (_i = 1; _i <= 100; _i++){ _results.push(_i); }
    return _results;
  }).apply(this).reduce(function(x, y) {
    return x + y;
  }), 2) - (function() {
    _results1 = [];
    for (_j = 1; _j <= 100; _j++){ _results1.push(_j); }
    return _results1;
  }).apply(this).map(function(x) {
    return Math.pow(x, 2);
  }).reduce(function(x, y) {
    return x + y;
  });

  console.log(res);

}).call(this);
