// Generated by CoffeeScript 1.6.3
(function() {
  var res, sum, _i, _results;

  res = 0;

  sum = (function() {
    _results = [];
    for (_i = 1; _i <= 999; _i++){ _results.push(_i); }
    return _results;
  }).apply(this).filter(function(x) {
    return x % 3 === 0 || x % 5 === 0;
  }).reduce(function(x, y) {
    return x + y;
  });

  res = sum;

  console.log(res);

}).call(this);
