// Generated by CoffeeScript 1.6.3
(function() {
  var M, i, j, p, res;

  res = 0;

  M = 2000000;

  p = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= M ? _i <= M : _i >= M; i = 0 <= M ? ++_i : --_i) {
      _results.push(i);
    }
    return _results;
  })();

  p[0] = p[1] = 0;

  i = 2;

  while (Math.pow(p[i], 2) <= M) {
    j = 2;
    while (p[i] * j <= M) {
      p[p[i] * j] = 0;
      j++;
    }
    i++;
    while (p[i] === 0) {
      i++;
    }
  }

  res = p.reduce(function(x, y) {
    return x + y;
  });

  console.log(res);

}).call(this);
