// Generated by CoffeeScript 1.6.3
(function() {
  var fact, res;

  res = 0;

  fact = function(n) {
    if (n === 1) {
      return 1;
    }
    return n * fact(n - 1);
  };

  res = fact(40) / (fact(20) * fact(20));

  console.log(res);

}).call(this);
