// Generated by CoffeeScript 1.6.3
(function() {
  var d, dmax, f, factors, h, i, j, res, s, stmp, _i, _j, _k, _l, _len;

  res = 0;

  dmax = 20;

  d = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 1; 1 <= dmax ? _i <= dmax : _i >= dmax; i = 1 <= dmax ? ++_i : --_i) {
      _results.push(0);
    }
    return _results;
  })();

  s = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 1; 1 <= dmax ? _i <= dmax : _i >= dmax; i = 1 <= dmax ? ++_i : --_i) {
      _results.push(0);
    }
    return _results;
  })();

  factors = function(x) {
    var fact;
    fact = [1];
    d = 2;
    while (x > 1) {
      if (x % d === 0) {
        fact.push(d);
        x /= d;
      } else {
        d++;
      }
    }
    return fact;
  };

  for (h = _i = 1; 1 <= dmax ? _i <= dmax : _i >= dmax; h = 1 <= dmax ? ++_i : --_i) {
    stmp = (function() {
      var _j, _results;
      _results = [];
      for (i = _j = 1; 1 <= dmax ? _j <= dmax : _j >= dmax; i = 1 <= dmax ? ++_j : --_j) {
        _results.push(0);
      }
      return _results;
    })();
    f = factors(h);
    for (_j = 0, _len = f.length; _j < _len; _j++) {
      j = f[_j];
      stmp[j - 1]++;
    }
    for (j = _k = 1; 1 <= dmax ? _k <= dmax : _k >= dmax; j = 1 <= dmax ? ++_k : --_k) {
      if (stmp[j - 1] > s[j - 1]) {
        s[j - 1] = stmp[j - 1];
      }
    }
  }

  res = 1;

  for (j = _l = 1; 1 <= dmax ? _l <= dmax : _l >= dmax; j = 1 <= dmax ? ++_l : --_l) {
    res *= Math.pow(j, s[j - 1]);
  }

  console.log(res);

}).call(this);
