// Generated by CoffeeScript 1.6.3
(function() {
  var a, b, fib, res, sum, _ref;

  res = 0;

  fib = [1, 1];

  a = 1;

  b = 1;

  while (b <= 4000000) {
    _ref = [b, a + b], a = _ref[0], b = _ref[1];
    fib.push(b);
  }

  sum = fib.filter(function(x) {
    return x % 2 === 0;
  }).reduce(function(x, y) {
    return x + y;
  });

  res = sum;

  console.log(res);

}).call(this);
